"""
Liquid City backend entrypoint.

Run locally with:
    uvicorn app.main:app --reload

Swagger docs are auto-generated by FastAPI at /docs.
"""

import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv

from app.api import (
    events, crowd, roads, partners, routes, recommendations, simulation, admin,
    questionnaire, planning, weather, digital_twin, social_signals
)

load_dotenv()

app = FastAPI(
    title="Liquid City API",
    description="Smart city / event crowd management backend: weather-driven digital twin, simulation, ML predictions, and recommendations.",
    version="1.1.0",
)

# CORS is configurable via env var for local frontend development, e.g.
# CORS_ORIGINS=http://localhost:3000,http://localhost:5173
cors_origins = os.getenv("CORS_ORIGINS", "*")
origins = ["*"] if cors_origins.strip() == "*" else [o.strip() for o in cors_origins.split(",")]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(events.router)
app.include_router(crowd.router)
app.include_router(roads.router)
app.include_router(partners.router)
app.include_router(routes.router)
app.include_router(recommendations.router)
app.include_router(simulation.router)
app.include_router(admin.router)
app.include_router(questionnaire.router)
app.include_router(planning.router)
app.include_router(weather.router)
app.include_router(digital_twin.router)
app.include_router(social_signals.router)


@app.get("/", tags=["health"])
def root():
    return {"message": "Liquid City API with Weather-Driven Digital Twin is running", "docs": "/docs"}


@app.get("/health", tags=["health"])
def health():
    return {"status": "ok"}
